### ISSUE TITLE
Uncaught Error: Unencoded <Line: 1Column: 1Char: <

### ISSUE THREAD

**Issue by Colillas02** [aerhard/linter-autocomplete-jing#64]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.52.0 x64
**Electron**: 6.1.12
**OS**: Unknown Windows version
**Thrown From**: [linter-autocomplete-jing](https://github.com/aerhard/linter-autocomplete-jing) package 0.8.4

### Stack Trace

Uncaught Error: Unencoded <
Line: 1
Column: 1
Char: <

```
At events.js:177

Error: Unencoded <
Line: 1
Column: 1
Char: <
    at error (/packages/linter-autocomplete-jing/node_modules/sax/lib/sax.js:651:10)
    at strictFail (/packages/linter-autocomplete-jing/node_modules/sax/lib/sax.js:677:7)
    at SAXParser.write (/packages/linter-autocomplete-jing/node_modules/sax/lib/sax.js:1080:13)
    at SAXStream.write (/packages/linter-autocomplete-jing/node_modules/sax/lib/sax.js:239:18)
    at ReadableString.ondata (_stream_readable.js:713:22)
    at ReadableString.emit (events.js:200:13)
    at ReadableString.Readable.read (_stream_readable.js:508:10)
    at flow (_stream_readable.js:977:34)
    at resume_ (_stream_readable.js:958:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
```

### Commands

```
     -7:59.7.0 core:delete (input.hidden-input)
     -7:56.8.0 core:backspace (input.hidden-input)
  3x -7:54.4.0 editor:newline (input.hidden-input)
 16x -7:47.8.0 core:backspace (input.hidden-input)
     -7:41.4.0 editor:newline (input.hidden-input)
 13x -7:40.7.0 core:backspace (input.hidden-input)
     -2:48.2.0 core:delete (input.hidden-input)
     -2:42.7.0 intentions:highlight (input.hidden-input)
     -2:42.5.0 symbols-view:toggle-file-symbols (input.hidden-input)
     -2:36.7.0 core:move-up (input.hidden-input)
     -2:36.4.0 editor:newline (input.hidden-input)
     -2:30.2.0 core:backspace (input.hidden-input)
     -2:29 autocomplete-plus:confirm (input.hidden-input)
     -2:29 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
```

### Non-Core Packages

```
busy-signal 2.0.1 
html-tag-auto-complete 2.0.0 
intentions 1.1.5 
language-dtd 0.2.1 
linter 3.1.1 
linter-autocomplete-jing 0.8.4 
linter-ui-default 2.1.2 
linter-xmllint 1.4.4 
open-in-browser 0.5.2 
xml-formatter 0.13.0 
```

**Comment by aerhard** [comment]
The error must be caused by a different package since the call stack includes the `SAXStream` from `sax-js` which we don't use. The fact that the error is thrown from the `sax-js` dependency of the `linter-autocomplete-jing` package is probably due to dependency deduplication in Atom.

**Comment by aerhard** [comment]
There's an open issue about this error at the `linter-xmllint` repo: https://github.com/AtomLinter/linter-xmllint/issues/106
